### ISSUE TITLE
any cleanup opportunities to reduce disk?

### ISSUE THREAD

**Issue by ghost** [connorlanigan/unrealengine-docker#3]
Pulling the latest unreal engine its using almost 100GB of disk! Are there any folders inside UnrealEngine-master that can be trimmed/deleted after successful build? For instance ./Engine/Source is 24GB, do we need it at runtime?

Or are all folders necessary during runtime?

**Comment by connorlanigan** [comment]
Hi!
There is unfortunately no easy way of finding out which files are needed after the build and which are not needed. The Editor might access files that are outside of the build output, so I can't say whether it is safe to delete any of them.

That said, the Unreal Engine build tools also support generating a variant that is called an "Installed Build" ([see Epic's documentation on this](https://docs.unrealengine.com/4.26/en-US/ProductionPipelines/DeployingTheEngine/UsinganInstalledBuild/)). The Installed Build is intended to be distributed (e.g. inside a company), and is independent of its source files. This might be what you're looking for.

Unfortunately, this project currently does _not_ support generating an Installed Build, and I don't have plans to add support.

However, in my research I discovered that there are two other projects that deal with creating/using an Installed Build of the Unreal Engine Editor on Linux:
- [ue4-docker](https://docs.adamrehn.com/ue4-docker), especially its [__ue4-minimal__ variant](https://docs.adamrehn.com/ue4-docker/building-images/available-container-images#ue4-minimal).
Its description says: _"Contains the absolute minimum set of components required for use in a Continuous Integration (CI) pipeline, consisting of only the build prerequisites and __an Installed Build of the Engine.__"_ (however, I don't know if this includes the Editor or just the Engine)
- [Unreal Containers](https://unrealcontainers.com), especially its use case articles "[Linux Installed Builds](https://unrealcontainers.com/docs/use-cases/linux-installed-builds)" and "[Linux Sandboxed Editor](https://unrealcontainers.com/docs/use-cases/linux-sandboxed-editor)"

I have not yet used either of them, so I can't really give a recommendation and I don't know whether they are indeed suitable for this goal, but from their documentation they look very promising.

I hope this can help you in your further research. Good luck! :)
